[package]
name = "tauri-plugin-keyring"
version = "0.1.0"
authors = ["Huakun Shen"]
description = "A tauri plugin wrapper for the keyring crate"
license = "MIT"
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-keyring"

[dependencies]
tauri = { version = "2.5.1" }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
keyring = { git = "https://github.com/open-source-cooperative/keyring-rs.git", rev = "9d1b02ff4c9fd1ff125c71f252c14b9ed7313fcb", features = [
    "apple-native",
    "windows-native",
    "secret-service",
] }

[build-dependencies]
tauri-plugin = { version = "2.3.0", features = ["build"] }
